# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: yokolet's notelets
email: yokolet@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Notes about programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yokolet
github_username:  yokolet
google_analytics: UA-761764-8

github:
  is_project_page: true
  repository_url: https://github.com/yokolet/yokolet.github.com
  repository_name: yokolet.com
  owner_url: https://github.com/yokolet
  owner_name: Yoko Harada

favicon: true
favicon_location: "/assets/image/favicon.ico"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

# pagination settings
pagination:
  enabled: true
  collection: 'posts'
  per_page: 12
  permalink: '/page/:num/'
  sort_reverse: true
  sort_field: 'date'
  trail:
    before: 2
    after: 2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - tmp
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
